### ISSUE TITLE
legacy_vnode_routing should default to true for new installs

### ISSUE THREAD

**Issue by jonmeredith** [basho/riak_core#147]
The legacy_vnode_routing app.config setting controls whether the new 1.1 vnode proxy code is used or the pre-1.1 vnode master code.

For new installs it should be set true - make sure it is set in the rel/files/app.config setting. 

Once clusters are all upgraded to 1.1.0 and above the config item should be added manually.

**Comment by rzezeski** [comment]
Does this issue still apply given the new capabilities system?  Is there any action we need to take?

**Comment by rzezeski** [comment]
I'm going to close this for now because I'm pretty sure the capabilities system makes this obsolete.  Please reopen if I'm wrong.
