### ISSUE TITLE
riak_core_vnode_manager blocks on vnode startup

### ISSUE THREAD

**Issue by jonmeredith** [basho/riak_core#150]
riak_core_vnode_manager is unresponsive while vnodes are being started by the vnode_sup (as it blocks in start_child).  This should be done asynchronously as it causes timeouts in other parts of the system - e.g. stats.

**Comment by jrwest** [comment]
this has been addresssed: https://github.com/basho/riak_core/blob/master/src/riak_core_vnode_manager.erl#L570-L605
