### ISSUE TITLE
riak-admin wait-for-service riak_kv <bad_node_name> does not return error [JIRA: RIAK-2802]

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak_core#151]
Running riak-admin wait-for-service riak_kv with a bad node name (i.e. localhost) return:

riak_kv is not up: []

No indication that this is a bad node name.  Suggest putting logic in to check node name for cluster membership or ability to ping.

Identified in 1045 during upgrade from 0.14 to 1.1.1 (https://help.basho.com/tickets/1045)

**Comment by jrwest** [comment]
verified this still occurs on master today. I've actually been bit by this working on some automated perf testing. this should be fixed in the next release or two so it will be left open.

**Comment by slfritchie** [comment]
@jrwest @bsparrow435 @deanproctor Hrm, since Dean's recent PR #385 was recently withdrawn without merging, what's the New Plan?

**Comment by jrwest** [comment]
@slfritchie @deanproctor opened https://github.com/basho/riak/pull/394 to handle the case where no node name is provided. I agree w/ @evanmcc that handling the invalid node-name should probably be handled here in core. I don't think we have plans for 2.0 (although maybe we will get to it right now its on the "Next Release + 1" milestone)

**Comment by evanmcc** [comment]
Yeah, I think that this is an easy polish thing that we should address in
the harden/polish post-ricon phase.

**Comment by jrwest** [comment]
not happening for `2.0-*` but moving to `2.0.1` since I still think this is a good/quick/easy/etc fix.

**Comment by bsparrow435** [comment]
Fixed on develop.
