### ISSUE TITLE
riak_core_handoff_sender not accepted {error, vnode_shutdown} message

### ISSUE THREAD

**Issue by ghost** [basho/riak_core#160]
2012-03-30 15:09:23 =ERROR REPORT====
Error in process <0.29050.246> on node 'riak@192.168.1.1' with exit value: {{badmatch,{error
,vnode_shutdown}},[{riak_core_handoff_sender,'-start_fold/5-fun-1-',9}]}

**Comment by jrwest** [comment]
not an ongoing issue. closing. if it resurfaces please open a new issue.
