### ISSUE TITLE
Don't read ring files from the future

### ISSUE THREAD

**Issue by Vagabond** [basho/riak_core#162]
If a ringfile is written with a sufficiently skewed timestamp, subsequent ring updates will be ignored on node restart until the ring file timestamp is no longer is in the future. This can cause very surprising behaviour,

A simple way to replicate is simply to change the 'year' part of the ringfile's timestamp to a year in the future, change some ring configs, and restart the node.

Better behaviour would at least be to warn about a ring file from the future, or refuse to load it at all.

**Comment by jrwest** [comment]
marked as bug and that there are intentions to fix in near future.

**Comment by slfritchie** [comment]
@Vagabond @jrwest Time for some belated repo curating ... is there any plan to fix this for Riak 2.0? ... It seems to me that @rzezeski's reference to this issue number was a typo?  Because I don't see anything in that commit that deals with ring files.

**Comment by Vagabond** [comment]
I've no intent to fix it in 2.0.

**Comment by rzezeski** [comment]
@slfritchie This is from GitHub automatically linking because of the `#162` in the commit message.  I have no involvement in this ticket.  Well...I guess that isn't true anymore :)

**Comment by jrwest** [comment]
@slfritchie no intent for 2.0 that I know of. its marked "Next Release + 1" right now.

**Comment by jrwest** [comment]
moved to `2.1` milestone
