### ISSUE TITLE
Expose "services" command over HTTP

### ISSUE THREAD

**Issue by seancribbs** [basho/riak_core#164]
For automated health-check tools (nagios, load-balancers, etc) it would be incredibly useful expose which services are up on a node. A webmachine resource that fronts `riak_core_node_watcher:services()` (or an addition to the stats resource) would greatly help this.

**Comment by jrwest** [comment]
speaking w/ @evanmcc we think this is a good addition that should be done in the next two releases. leaving this open.

**Comment by seancribbs** [comment]
@jrwest @evanmcc Maybe move to top-level or riak_api as a feature?

**Comment by jrwest** [comment]
agreed. esp since we are moving HTTP out of core (via removing webmachine). moved: https://github.com/basho/riak_api/issues/30
