### ISSUE TITLE
chstate & chstate_2 records extraction

### ISSUE THREAD

**Issue by yrashk** [basho/riak_core#165]
Hi,

is there any chance to get those ring records extracted to some (even internal) include file? We are constructing some bogus rings and therefore need direct access to those structures. Right now we just copy-pasted them, but that doesn't sound like a good solution long term.

**Comment by jrwest** [comment]
I'd like to close this issue out. This is a good improvement for tests (some tests in Riak do the same thing) but we don't have near-term plans to change it. Patches welcome, I'll be happy to review.

**Comment by slfritchie** [comment]
@yrashk Is this an itch that you still need to scratch?

**Comment by yrashk** [comment]
nope

**Comment by slfritchie** [comment]
Thanks, Yurii, closing.
