### ISSUE TITLE
Ability to delete custom bucket properties

### ISSUE THREAD

**Issue by ghost** [basho/riak_core#197]
Right now, while we have the ability in `riak_core_bucket` to set bucket properties:

``` erlang
%% @spec set_bucket(riak_object:bucket(), BucketProps::riak_core_bucketprops()) -> ok
%% @doc Set the given BucketProps in Bucket.
set_bucket(Name, BucketProps0) ->
    case validate_props(BucketProps0, riak_core:bucket_validators(), []) of
        {ok, BucketProps} ->
            F = fun(Ring, _Args) ->
                        OldBucket = get_bucket(Name),
                        NewBucket = merge_props(BucketProps, OldBucket),
                        {new_ring, riak_core_ring:update_meta({bucket,Name},
                                                              NewBucket,
                                                              Ring)}
                end,
            {ok, _NewRing} = riak_core_ring_manager:ring_trans(F, undefined),
            ok;
        {error, Details} ->
            lager:error("Bucket validation failed ~p~n", [Details]),
            {error, Details}
    end.
```

We do not have the ability to delete custom bucket properties. Since these are stored in the ring, this adds up when creating hundreds/thousands of buckets with custom properties. A use case that has been seen is where certain buckets require the search post-commit hook, and others do not.

Right now, even if you delete all the keys and attempt to set the bucket properties back to default, it still will be kept in the ring.

It should be feasible to delete the dict key for a certain bucket's properties, and have it revert back to default properties.

**Comment by jerith** [comment]
The slowdown in setting bucket properties when there is already a lot of metadata is quite extreme. See https://gist.github.com/2978270 for a script that demonstrates this.

**Comment by slfritchie** [comment]
All constituent tickets reviewed, +1 to merge, thanks!
- riak_core #197
- riak_core #202
- riak_core #248
- riak_test #81
- riak_kv   #422
