### ISSUE TITLE
add HTTP resource for transfers status

### ISSUE THREAD

**Issue by rzezeski** [basho/riak_core#200]
In reference to Mark Smith's comments on [this blog post](http://basho.com/blog/technical/2012/06/25/Riak-Admin-Transfers-in-1-2-Release/).

The transfer status information should be exposed via HTTP so that external tools may easily obtain the data in it's raw form.  Currently a user would either have to write some Erlang or parse human-friendly output on the command line.  Neither option is very accessible to most users.

Implementation Note: I imagine just pulling back the raw status proplist and exposing that as JSON would do the trick.

**Comment by evanmcc** [comment]
I imagine we can close this as the clients team wants to move away from HTTP, although if we still think that it's useful, we can just repoint at PBC.

Personally I am dubious as to its utility (but the link has bitrotted, so I can't read the comment's reasoning), in terms of just exposing transfers.  I can see the use of some cut-down ring status though, e.g.
{"ring_ready":true,
"transfers_outstanding":false} 
That said, experience suggests that few users have their clusters automated enough to take advantage of this.

**Comment by rzezeski** [comment]
I agree that this should be closed.  We are moving towards a single protocol that is not HTTP.  We should provide the information there if people start asking for it.
