### ISSUE TITLE
Considerations on the usability of various reports of ring size.

### ISSUE THREAD

**Issue by fprimex** [basho/riak_core#221]
There are a few places users typically look to learn a cluster's ring size, for example: app.config file, status, /stats

The presence of the ring_creation_size setting in the app.conifg file as well as its presence in status (and elsewhere) can be misleading for those interested not in the ring creation size, but the size of the ring of the current running cluster. The information desired in that case is instead ring_num_partitions.

The purpose of this ticket is to raise the question of how the usability and reporting could be improved to further express that ring_creation_size is not the actual ring size, and should not be used as such. Certainly these 'variables' are what they say they are, and _should_ be treated as such, but could improvements be made so that mistakes could be avoided in cases where, for whatever reason (frequently an error), they do not agree.
- Should the reporting of ring_creation_size be deprecated and removed for clarity?
- Are there any portions of code relying on ring_creation_size and ring_num_partitions to match that shouldn't be?
- Should Riak check for a disagreement in these values on startup and log or report it?
- Should the `riak-admin ringready` or another command be augmented to report a disagreement in these values?

**Comment by evanmcc** [comment]
I feel like we should close this; This issue is general and doesn't point to a particular solution.  I think that this is a valid support issue, but we should generate a particular fix and open an issue for that.

**Comment by jrwest** [comment]
@evanmcc I plan to add some ring size output to ring-status since we have added the ability to resize. Closing for reasons mentioned above.
