### ISSUE TITLE
No open source license specified

### ISSUE THREAD

**Issue by freerobby** [basho/riak_core#235]
I'm interested in using riak-core for an open source project that would (hopefully) be MIT-licensed. I checked the Readme and associated documentation but could not find a stated OSL. Assuming riak-core is intended for open source use, can Basho issue a license for it accordingly?

**Comment by seancribbs** [comment]
All our open-source software, including riak_core, is Apache 2-licensed. It looks like we are simply missing the LICENSE file from this repo, but the comment-header on every file is the Apache one.

**Comment by freerobby** [comment]
Ah, thank you Sean.
