### ISSUE TITLE
If the handoff port is taken, handoffs fail with uninformative errors

### ISSUE THREAD

**Issue by evanmcc** [basho/riak_core#238]
Note that if two of our ports (SSL and handoff was the wild case) are the same on the receiving node, this is all you get on the sender:

2012-10-05 17:17:47.823 [error] <0.17731.38>@riak_core_handoff_sender:start_fold:207 
                 ownership_handoff transfer of riak_kv_vnode from 'prod-riak10@192.168.26.217' 
                 456719261665907161938651510223838443642478919680 to 'prod-riak0@192.168.26.180' 
                 456719261665907161938651510223838443642478919680 failed because of TCP recv timeout

these repeat constantly.  On the receiver, you get nothing at all.

We should catch this on the receiver and provide better error messages.  If there's a catchable error on the sender, we should improve the message there as well.

Handoff for kv never happens, and nodes that join can never leave and must be force-removed.

**Comment by scalp42** [comment]
@evanmcc helped us figure it out and I thank him a lot for the help.

Here is a patch for now we're using to prevent Riak from starting and force unique ports :

https://github.com/scalp42/riak/commit/8d20478bdae17f2fa4cbb84f22602bb7231ae3b6

Let me know if a pull request is better and I'll rewrite it.

Thanks again!

**Comment by evanmcc** [comment]
Going to close this one, the fix rightly goes in riak.
