### ISSUE TITLE
gen_server call review

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_core#267]
While trying to start Riak under Valgrind, I encountered a gen_server:call() timeout exception which causes an application startup failure which prevents Riak from starting successfullly.

The culprit for my particular case is `riak_core_stat_cache.erl`:

```
 register_app(App, {M, F, A}, TTL) ->
    gen_server:call(?SERVER, {register, App, {M, F, A}, TTL}).
```

This is likely one of many uses of `gen_server:call/2` when we really ought to be using the 3-arity version with an infinity timeout.

**Comment by slfritchie** [comment]
Time for some belated repo curating ... waiting for movement on PR #346.

**Comment by jrwest** [comment]
#346 merged in some form. closing.
