### ISSUE TITLE
Dependencies cleanup?

### ISSUE THREAD

**Issue by yrashk** [basho/riak_core#272]
Hi,

Some of us riak_core users have been discussing the list of dependencies riak_core has, and to our best understanding some of them don't exactly belong to riak_core itself (webmachine, mochiweb, protobuffs, etc.).

Do you guys think there is a chance we can do some cleanup in that area?

Thanks

**Comment by tsloughter** [comment]
+1, I've started with it on a fork https://github.com/tsloughter/riak_core

**Comment by omarkj** [comment]
+1

**Comment by seancribbs** [comment]
1. `protobuffs` is needed for handoff. I don't know what our engineers are planning for the next revision, but this may change.
2. `webmachine` and friends will likely move to `riak_api` when we have a better idea of how to reorganize the startup  and shutdown sequence. Ideas are welcome in this area.

**Comment by evanmcc** [comment]
cc @chardan re handoff

**Comment by yrashk** [comment]
@seancribbs seems to be a tricky part with protobuffs — can't find any direct reference to it besides the riak_core.proto file

**Comment by russelldb** [comment]
What is the aim, and what are your criteria for 'belongs'? Folsom provides stats, riak_core provides stats. I see in @tsloughter's fork riak_core does not have stats any longer. Is that OK? And what is the _cost_ of the deps you want to cut, what do you gain from cutting them?

**Comment by seancribbs** [comment]
@yrashk I guarantee you handoff will not work without it. Look for references to riak_core_pb

**Comment by yrashk** [comment]
@seancribbs I am just saying that it's a tricky "hard to spot" dependency :)

**Comment by tsloughter** [comment]
Yea, discovered the protobuff issue for handoffs today :). 

So that definitely has to be added back unless it was made possible to handoff with a binary or something.

As for folsom, I was undecided on that. I use it myself for stats, so would end up with it in a riak_core project anyway, but if core is to just provide the building blocks for a distributed system someone may want to use another stat counter.

My gutting was more of an experiment, but I think necessary in some places.

**Comment by tsloughter** [comment]
@seancribbs I'm trying to find where the protobuff encoding is actually done for a handoff. Could you point me to it? I'm curious why protobuffs are used instead of simply Erlang binary terms.

**Comment by yrashk** [comment]
...or a simple binary with three sized-encoded binaries?

**Comment by seancribbs** [comment]
Sorry, maybe the protobuffs are something that didn't get untangled when riak_core was extracted. Honestly, it's been over 2 years, and I wasn't involved at the time, so I don't know.

**Comment by yrashk** [comment]
speaking about webmachine, now that parametrized modules are gone, one can't (seemingly) build riak_core on R16 because basho's mochiweb hasn't been updated

**Comment by evanmcc** [comment]
On a new checkout? I thought out had gone into master.

**Comment by evanmcc** [comment]
#355 partially fixes this. I think that mochiweb is also or already removed, and protobuffs will be removed eventually.

**Comment by slfritchie** [comment]
Time for some belated repo curating ... is it worth keeping this issue open?

**Comment by jrwest** [comment]
the dependencies mentioned are removed I believe. I'm going to close this issue out. If there is future discussion to be had, please feel free to re-open or leave a comment.
