### ISSUE TITLE
Core console mentions riak-admin script

### ISSUE THREAD

**Issue by engelsanchez** [basho/riak_core#278]
For example, when called through riak's 'riak-admin transfer_limit' command, for example.
However, the admin script for the actual core app will likely be different. At the very least we should make it possible for a core app to customize that and maybe other messages.

**Comment by jrwest** [comment]
looks like there is already an issue for this here: https://github.com/basho/riak_core/issues/263

**Comment by engelsanchez** [comment]
You da man, Jordan. Closing this.
