### ISSUE TITLE
Do not fail handoffs silently if the remote node doesn't have the appropriately named service

### ISSUE THREAD

**Issue by yrashk** [basho/riak_core#279]
https://github.com/basho/riak_core/blob/master/src/riak_core_vnode_manager.erl#L628

This line makes handoffs fail silently and therefore hard to debug. If this line also emitted a debug/info log, it'd be so much easier to not waste a couple of hours :)

If you like this idea, I can send a pull req.

**Comment by jonmeredith** [comment]
It could have a debug statement - but it would get pretty noisy when the target node was down.

**Comment by yrashk** [comment]
We can do an additional check — we can check whether the node is actually up. WDYT?

**Comment by yrashk** [comment]
(and only do a debug statement if it _is_ up)

**Comment by jonmeredith** [comment]
During startup and shutdown you'll still legitimately go through that code path.   I'd be ok with an info message if it included a message like "handoff to {{node}} aborted due to service down, perhaps node is starting/stopping"

What was the issue you were debugging?

**Comment by yrashk** [comment]
My issue was that my code didn't match up to certain expectations that riak_core had (it always forces you to use your app name as a service name [the should_handoff part] and it always assumes your top supervisor is called yourapp_sup). It was silently not doing handoffs in my case and I lost a couple of hours tracing everything through.

**Comment by slfritchie** [comment]
Time for some belated repo curating ... Yurii, do you have a PR for this?

**Comment by yrashk** [comment]
Nope

**Comment by slfritchie** [comment]
Okey-dokey, thanks!  Closing.
