### ISSUE TITLE
riak_core_service_mgr:unregister should take version arg

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_core#303]
At present, you can register a protocol id multiple times, with different arguments and modules. However, the unregister API will remove all registered modules of that protocol id. So, there is no way to unregister discrete versions. Please add that ability to the API.

**Comment by slfritchie** [comment]
Time for some belated repo curating ... is there any plan to fix this for Riak 2.0?

**Comment by jrwest** [comment]
`riak_core_service_mgr` no longer exists in `riak_core`. closing.
