### ISSUE TITLE
Fix riak_core_connection_mgr_stats timestamp formatting

### ISSUE THREAD

**Issue by bookshelfdave** [basho/riak_core#309]
riak-repl clusterstats
RPC to 'riak@brawl' failed: {'EXIT',
                                                           {function_clause,
                                                            [{riak_core_connection_mgr_stats,
                                                              format_stat,
                                                              [{riak_conn_mgr_stats_stat_ts,
                                                                1365529127}],
                                                              [{file,
                                                                "src/riak_core_connection_mgr_stats.erl"},
                                                               {line,61}]},
                                                             {riak_core_connection_mgr_stats,
                                                              '-get_consolidated_stats/0-lc$^0/1-0-',
                                                              1,
                                                              [{file,
                                                                "src/riak_core_connection_mgr_stats.erl"},
                                                               {line,54}]},
                                                             {riak_core_connection_mgr_stats,
                                                              get_consolidated_stats,
                                                              0,
                                                              [{file,
                                                                "src/riak_core_connection_mgr_stats.erl"},
                                                               {line,54}]},
                                                             {riak_repl_console,
                                                              clusterstats,1,
                                                              [{file,
                                                                "src/riak_repl_console.erl"},
                                                               {line,203}]},
                                                             {rpc,
                                                              '-handle_call_call/6-fun-0-',
                                                              5,
                                                              [{file,
                                                                "rpc.erl"},
                                                               {line,203}]}]}}

**Comment by bookshelfdave** [comment]
see https://github.com/basho/riak_core/pull/310

**Comment by slfritchie** [comment]
Time for some belated repo curating ... Dave, it seems to my bleary eyes that this ticket can be closed?

**Comment by bookshelfdave** [comment]
thanks @slfritchie
