### ISSUE TITLE
riak_core_vnode_manager:sync_spawn_command hung

### ISSUE THREAD

**Issue by zhangjiayin** [basho/riak_core#353]
https://github.com/zhangjiayin/recomet/blob/master/src/recomet.erl#L42
when I use   riak_core_vnode_master:sync_command under 100000 concurrency and mochiweb the function will timeout 
and  sync_spawn_command will hung

any one can help me

**Comment by zhangjiayin** [comment]
does any one focus on  this issue?

**Comment by slfritchie** [comment]
Time for some belated repo curating ... sorry about the delay, @zhangjiayin.  Could you please update the 'recomet.erl' link in the problem description?  It looks like you have reorganized the file hierarchy of your repo since you opened this issue.

**Comment by zhangjiayin** [comment]
It's long time .
I've delete my repo on github for security reason.
and riak_core  have update so many code .
I will reopen this issus if  it occured with new version
