### ISSUE TITLE
Apply `set_bucket` fix to 1.4 and develop

### ISSUE THREAD

**Issue by rzezeski** [basho/riak_core#366]
Apply fix #365 to the 1.4 and develop branches.

**Comment by jrwest** [comment]
after further investigation this needs to be fixed for the `1.4` branch but `develop`. `develop` passes the `Ring`, like the change to #365 does: https://github.com/basho/riak_core/blob/develop/src/riak_core_bucket.erl#L84-L91

Marking for `1.4.9` milestone

**Comment by rzezeski** [comment]
This has finally been patched in 1.4; closing.
