### ISSUE TITLE
Further Review of DVVSets in Cluster Metadata

### ISSUE THREAD

**Issue by jrwest** [basho/riak_core#374]
As mentioned during [review](https://github.com/basho/riak_core/pull/363#issuecomment-23981530) of basho/riak_core#363 the included `dvvset` module was only given a cursory review. A decision on whether to continue using it or to convert it to using plain old vclocks and further review of `dvvset.erl` if it is chosen is necessary.

**Comment by jrwest** [comment]
This is probably to late for 2.0 in general. We do need to revisit if we want to continue to use these clocks long term. Marked for `2.0.1` but may slip to `2.1`

**Comment by russelldb** [comment]
My opinion is that, since DVVSets are used as the model for the riak_object enhanced causality tracking, they've been quickchecked.

**Comment by jrwest** [comment]
Aren't they different in  riak_object (our dots impl vs the original dvvset.erl used by cluster meta)?

**Comment by russelldb** [comment]
Sure, different, but similar enough that one is the model for the other. Pretty sure that the model and the thing it models get tested in equal measure with EQC.

**Comment by jrwest** [comment]
thanks, in that case I believe we can close. and for completeness, the model being referred to is https://github.com/basho/riak_kv/blob/develop/test/riak_object_dvv_statem.erl
