### ISSUE TITLE
Should make_fold_req and is_request_forwardable match?

### ISSUE THREAD

**Issue by beerriot** [basho/riak_core#420]
The functions `riak_core_util:make_fold_req/2` and `riak_core_vnode:is_request_forwardable/1` seem to be at odds with each other, with respect to `#riak_core_fold_req_v1{}`. The `is_request_forwardable` function will return `true` for that record, but if `make_fold_req` decides to upgrade it to `#riak_core_fold_req_v2{}`, it sets the `forwardable` entry to `false` (and so `is_request_forwardable` returns false for the upgrade).

Given that there are no other changes made to the req during upgrade, and `riak_[kv|search|pipe]_vnode` all treat both records the same, should these functions match? What kind of behavior will we see if a v1 req is forwarded, but an upgraded v1 is not?

**Comment by slfritchie** [comment]
Lurking...

**Comment by jrwest** [comment]
This seems like a good resilience testing candidate. Marking for `2.0-RC` for now, along w/ testing/resilience tables.

**Comment by cmeiklejohn** [comment]
:+1:

**Comment by jrwest** [comment]
As I read through the code I don't see an issue. iirc this code was added such that we stop forwarding `?FOLD_REQ`s when we shouldn't so moving from `forwardable=true` to `forwardable=false` after upgrade is desirable -- we should have never been forwarding these in the first place. @slfritchie does that sound correct and if so can we close this out?

Tangentially, I wonder why we even needed a capability...new nodes should be able to handle forwarded `v1` requests (irrespective of if they upgrade them) and we should never forward `v2` requests so they will never reach a node that is unaware of the version. What am i missing?

**Comment by slfritchie** [comment]
> Tangentially, I wonder why we even needed a capability[....]

Isn't the capability there to avoid creating `v2` requests and sending them the normal, non-forwarding that most vnode ops take?

**Comment by jrwest** [comment]
ah right, in my haste I forgot the original source of the requests. so yes, we do want the capability. that said, I think we can still close out this issue as the intent is to no longer forward after we have upgraded. Do you agree?

**Comment by slfritchie** [comment]
Yes.  Closing.
