### ISSUE TITLE
'riak-admin wait-for-service' appears to loop inifinitely

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_core#427]
Using develop branches from today:

riak:

```
commit d008962bf77fee83bd7c5a3161c7168e5d571117
Author: Engel A. Sanchez <engel@basho.com>
Date:   Wed Sep 25 11:56:45 2013 -0400
```

riak_core:

```
commit 9ac2211dc5c5e02e75d88aca397d6afc0900ef95
Merge: 36437b6 b19ad3e
Author: Joe DeVivo <joe@devivo.com>
Date:   Mon Oct 14 13:55:59 2013 -0700
```

riak_kv:

```
commit 19c472eaf2d1fe919ff13119434803301cecace6
Author: Scott Lystig Fritchie <slfritchie@snookles.com>
Date:   Tue Oct 15 15:10:32 2013 +0900

    Add riak_kv.retry_put_coordinator_failure to priv/riak_kv.schema
```

I see the following when I use `make stage` then:

```
% touch rel/riak/log/console.log

% tail -F rel/riak/log/console.log | grep 'Wait complete for service riak_kv' &
[2] 77199 77200

% ./rel/riak/bin/riak start

% ./rel/riak/bin/riak-admin wait-for-service riak_kv dev@127.0.0.1
riak_kv is not up: []
riak_kv is not up: []
riak_kv is not up: []
2013-10-15 16:41:06.650 [info] <0.335.0>@riak_core:wait_for_service:481 Wait complete for service riak_kv (9 seconds)
2013-10-15 16:41:06.650 [info] <0.335.0>@riak_core:wait_for_service:481 Wait complete for service riak_kv (9 seconds)
riak_kv is not up: []
riak_kv is not up: []
riak_kv is not up: []
riak_kv is not up: []
riak_kv is not up: []
riak_kv is not up: []
^C
```

**Comment by engelsanchez** [comment]
My Riak won't start this morning in develop. Do you see these too? It seems current leveldb rejects a parameter passed in by hashtree as too low for a vnode:

09:22:12.432 [error] CRASH REPORT Process <0.3820.0> with 0 neighbours exited with reason: no match of right hand value {error,{db_open,"Invalid argument: Less than 10Mbytes per database/vnode"}} in hashtree:new_segment_store/2 line 520 in gen_server:init_it/6 line 328

**Comment by engelsanchez** [comment]
I'm looking into passing a new "internal DB" flag to level DB here. I saw that mentioned recently and I bet that's what's missing, so parameters don't get validated as if for a vnode database.

**Comment by jrwest** [comment]
It sounds like one of the mv-flex cache branches did not merge. The PR for riak it sounds like. 

Jordan

**Comment by jrwest** [comment]
That PR did merge so I wonder if your guys top level riak needs updating locally? I hit that error when testing w/o the change yesterday during review:

https://github.com/basho/riak/pull/406
https://github.com/basho/eleveldb/pull/73

EDIT: out of date or a bug, the basic issue is some options are not being passed for internal dbs.

**Comment by jrwest** [comment]
https://github.com/basho/riak/pull/406 has not been applied to `riak_ee` if you are using it, that may also be the case

**Comment by jrwest** [comment]
Ok less tired and dug into this a bit more: 

What I said above is correct (EE does need basho/#406) but also the options are not being passed for metadata hashtrees. This will cause problems when you try to write to a new cluster metadata prefix (when we open the tree). Working on a fix now.

**Comment by engelsanchez** [comment]
@slfritchie this should not happen anymore with latest Leveldb. Can we close this now?

**Comment by slfritchie** [comment]
Hm, I thought that I wasn't seeing the eleveldb startup errors, but lager's priority sorting may have been hiding them from me.  I pulled the latest & rebuilt, and I see "riak_kv is up", so ... closing, thanks!
