### ISSUE TITLE
Fails to compile with R16B

### ISSUE THREAD

**Issue by ethan-tqa** [basho/riak_core#449]
crypto:sha/1 has been deprecated in R16B, and thus make riak_core unable to be compiled. It can be easily change to crypto:hash(sha, StuffToEncrypt ).

**Comment by seancribbs** [comment]
We have already addressed this at least once. Can you point to a module/line number?

**Comment by cmeiklejohn** [comment]
I just went through the repository and the only places I found where the old-style crypto calls are being made are inside ifdef's which allow the compilation to succeed under R15B03 and below.  If you have a reproducible error, can you please re-open and paste the compilation failure you are experiencing.

**Comment by ethan-tqa** [comment]
I am using tag 1.4, roll ver 1.4.3, and the offending lines are in riak_core_util.erl:183, chash.erl:105 and merkerl.erl:327

**Comment by jrwest** [comment]
Riak Core 1.4 does not support `R16B`. The changes were made during this release cycle and have not been backported (I don't believe we intend to, but I could be incorrect on that): https://github.com/basho/riak_core/pull/348

**Comment by anish-mp** [comment]
I tried compiling riak_core  ( tag 1.4.4  ) using R16B03-1 (erts-5.10.4) [source] [64-bit]

The deprecated  crypto:sha/1  is used  in following files ( with line numbers)

src/merkerl.erl:327:    crypto:sha(term_to_binary(X)).
src/riak_core_util.erl:183:    Rand = crypto:sha(term_to_binary({make_ref(), os:timestamp()})),
src/chash.erl:105:    crypto:sha(term_to_binary(ObjectName)).

After changing 
           crypto:sha(  
             to  
         crypto:hash(sha,  
riak_core  1.4.4  compiles fine. 

Thanks

**Comment by anish-mp** [comment]
In src folder of riak_core , the following replacement shall be done to change crypto:sha to crypto:hash
In src folder of riak_core
grep crypto:sha\* \* | awk -F : '{ print $1 } ' | xargs -n 1 sed -i 's/crypto:sha(/crypto:hash(sha,/g'
