### ISSUE TITLE
Stuck handoff after disabling search

### ISSUE THREAD

**Issue by engelsanchez** [basho/riak_core#455]
It was reported that Riak ended up with handoff transfers stuck in the awaiting state through this sequence of actions:
- The cluster had search enabled, although search wasn't actively used
- Search merge index corruption was stalling handoffs
- Nodes were restarted to disable search, search data was removed
- Once back up, transfers that were waiting for search handoff to finish now are stuck in that state.

Maybe we need to do a bit more to detect invalid handoff state after situations like this.

**Comment by jrwest** [comment]
what do we want to do with this issue given search is deprecated. I'm inclined to close it. @rzezeski?

**Comment by rzezeski** [comment]
If we continue work on the 1.4.x series then this may be something we want to address. I personally would vote to take the lazy approach and wait until it becomes an issue for someone again.

**Comment by jrwest** [comment]
I'm going to go ahead and close this out. 1.4.x search is unlikely to see improvements, unless it affects users directly, and 2.0 search does not work in the same manner and does not have its own vnode, which is what would be stalling the handoff. Other riak_core applications could perhaps benefit (`riak_pipe` not really being one of them) but I don't see this as planned to be fixed. We can re-open if it comes back up.
