### ISSUE TITLE
Not all riak_core stats are available by all methods

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_core#474]
From @shino:

> > 1. riak-admin status is missing some stats that appear in the HTTP /stats
> >    4b. same for cluster-info dump of stats.
> 
> Drat, I forget the exact stats that Shino was looking for this

It was "dropped_vnode_requests_total".
Other than that, some (all?) riak_core's stats such as "gossip_received"
are missing in riak-admin status side.
cluster-info is also missing them.

**Comment by jrwest** [comment]
Marked for milestone `2.1` since its "future work" but probably a good candidate for a quick fix in a patch release.

**Comment by russelldb** [comment]
I think I did this already.

https://github.com/basho/riak_kv/pull/828

**Comment by jrwest** [comment]
agreed. closing

EDIT: also moved to `2.0-beta` since it was fixed this cycle
