### ISSUE TITLE
Plug background manager's EQC tests into Eunit.

### ISSUE THREAD

**Issue by buddhisthead** [basho/riak_core#485]
Right now the EQC test is run by hand, but it would be cool to have it run from eunit. We should do this before the release of 2.0

**Comment by jrwest** [comment]
Should be fixed for `2.0-RC` during testing

**Comment by cmeiklejohn** [comment]
Assigning to @jrwest.

**Comment by kellymclaughlin** [comment]
Do we still want to worry about this for RC since bg manager is now disabled by default?

**Comment by jrwest** [comment]
see the referenced PR above, its being reviewed and then I will close this out.

**Comment by kellymclaughlin** [comment]
> see the referenced PR anove, its being reviewed and then I will close this out.

Great, thanks!
