### ISSUE TITLE
Show default bucket type props on `bucket-type status`

### ISSUE THREAD

**Issue by lucperkins** [basho/riak_core#517]
Currently, the `props` associated with any user-created bucket type can be displayed using the `riak-admin bucket-type status <type>` command. This cannot, however, be done with the `default` type, which only returns `active` or `not active`. It might be useful to enable users to see the `default` configuration as well, as the only other way of doing so, AFAIK, is through HTTP (and maybe PBC).

**Comment by jrwest** [comment]
more than just useful I found it to be a bug, so here is a fix :) https://github.com/basho/riak_kv/pull/824

**Comment by jrwest** [comment]
fix should be included in pre14
