### ISSUE TITLE
Riak Streaming Mapreduce Not Reliably Outputting EOF Boundary

### ISSUE THREAD

**Issue by roncemer** [basho/riak_core#559]
In a production environment with 6 Riak servers running riak-1.4.8-1.x86_64 (Amazon Linux), I'm running into this error fairly regulary.  I used to see it infrequently, and the workaround was to narrow the time range for the query.

I'm doing streaming mapreduce over HTTP.  So the URL looks something like this:

http://<host>:<port>/mapred?chunked=true

Request headers look like this:
Content-Type: application/json

Query looks like this:
{
    "inputs":{
        "bucket":"ecapilog",
        "index":"\$key",
        "start":"2014-03-12 05:00:00",
        "end":"2014-03-12 06:00:00"
    },
    "query":[
        {"map":{"language":"erlang","module":"riak_kv_mapreduce","function":"map_object_value"}}
    ],
    "timeout":1800000
}

The BUG is that Riak is closing the socket without outputting the final EOF boundary (which is the normal boundary, with two extra '-' characters appended to it.  The RFCs are pretty clear on this; the EOF boundary is important.  But Riak is closing the socket without outputting the EOF boundary.

I check the Riak logs on all six servers, no errors.  So I has to be a bug in Riak.

All successful code paths MUST write the EOF boundary before closing the HTTP socket.  If Riak blows up while executing the query, it should at least log the error in one of its many and redundant log files.  Yet it is not logging any error.

I had been seeing this bug before, and the solution (although obviously ridiculous) was to narrow the time range of the query.  But honestly, Riak should be able to query an arbitrary time range without blowing up.  And if it does blow up, it should log the fact that it blew up.

In any event, Riak needs to NOT blow up on any query, regardless of the time range, and needs to ALWAYS output that final EOF boundary according to the RFC when doing streaming mapreduce.

This one is pretty urgent, it's actually messing up our targeting predictions which could easily be costing us thousands of dollars per day.

Please fix.

Thanks!
Ron

**Comment by seancribbs** [comment]
This issue was filed in the wrong place. [riak_kv](/basho/riak_kv/issues) provides the mapred interface.

**Comment by roncemer** [comment]
DId you move it to the correct place?  What is the new issue number?
