### ISSUE TITLE
Update ensemble bootstrap logic to enable consensus

### ISSUE THREAD

**Issue by jtuple** [basho/riak_core#571]
In basho/riak_ensemble#10, the clustering system for `riak_ensemble` was changed to require a manual step to enable the consensus system on a single node before joining nodes together into a cluster. This change was made to ensure that there is only ever a single logical root ensemble history. Joining nodes adopt the history from the single enabled node.

Thus, a user must now run `riak_ensemble_manager:enable().` from the console of Riak claimant to enable strong consistency.

We should change the bootstrap logic in `riak_core_claimant` to perform this step automatically. The primary challenge is ensuring only a single node ever performs that step, even in the presence of node failures/partitions.

One way to implement this is to have the current claimant wait for "ring ready" and then check for a ring metadata key that notes the consensus singleton node. If the key is missing, the claimant writes itself as the singleton and waits yet again for "ring ready". If the claimant sees itself as the singleton in a ready ring, the claimant then enables the consensus system. Likewise, the bootstrap logic would be updated to join nodes to the known singleton (based on the metadata value) rather than the current claimant.

/cc basho/riak#536

**Comment by michellep-basho** [comment]
Because there's a workaround ok to defer this until after 2.0 if it's addressed in the docs.

**Comment by jtuple** [comment]
The manual work-around is error prone and is a bit more complicated then as described in this issue given some corner cases. So, decided to just fix it properly. Pull-request basho/riak_core#601 is where the action is.

**Comment by jtuple** [comment]
Fixed in #601
