### ISSUE TITLE
SSL Configurations are Inconsistent between HTTP and PB Interfaces

### ISSUE THREAD

**Issue by hazen** [basho/riak_core#574]
Currently Cuttlefish and HTTP use the SSL key/cert/cacert file configurations from `riak_core`, but Protocol Buffers use the `riak_api` configuration.

**Comment by seancribbs** [comment]
It seems MDC relies on the setting being in `riak_core`. Seems we should go one of at least these ways:
1. Change MDC references to `riak_core` SSL configs to point to its own namespace. This is the most consistent (handoff has its own SSL settings, fwiw), but might cause backwards compatibility problems.
2. Change PB to lookup the setting in the `riak_core` namespace. This centralizes the setting, but I don't know the reasoning behind why it doesn't do this in the first place. It is slightly more consistent, but handoff would still be an outlier.
3. Make PB try `riak_api` for the setting(s) first, then `riak_core` if that's not present. This is most compatible, but doesn't solve the underlying issue.

Regardless, we should definitely reexamine `riak_core.schema` and `riak_api.schema` to see if there's some more consistency to be had.

**Comment by engelsanchez** [comment]
@seancribbs @jonmeredith could this cleanup be moved post RC?

**Comment by jonmeredith** [comment]
I'll defer to @seancribbs @joedevivo - less is more when it comes to shipping.

**Comment by seancribbs** [comment]
No, riak_api.\* SSL settings are not currently under cuttlefish, meaning we
get problems like this:
https://github.com/basho-labs/riak-ruby-vagrant/blob/master/advanced.config#L6-L10

On Mon, May 12, 2014 at 7:04 PM, Jon Meredith notifications@github.comwrote:

> I'll defer to @seancribbs https://github.com/seancribbs @joedevivohttps://github.com/joedevivo\- less is more when it comes to shipping.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/riak_core/issues/574#issuecomment-42903577
> .

## 

Sean Cribbs sean@basho.com
Software Engineer
Basho Technologies, Inc.
http://basho.com/

**Comment by seancribbs** [comment]
Resolved in basho/riak_api#60. Moving discussion there.
