### ISSUE TITLE
Bucket property validation

### ISSUE THREAD

**Issue by lukebakken** [basho/riak_core#576]
Tested with Riak 1.4.8.

Bucket properties that do not match existing atoms, such as `foobar` are disallowed. The following results in a `500` error code:

```
{error,badarg,
        [{erlang,list_to_existing_atom,["foobar"],[]},
```

However, you are allowed to set a bucket property like `expiry_secs`, which could be confusing to an end-user who believes they just set the bitcask expiration on a bucket.

Ideally, only valid bucket properties could pass validation.

**Comment by jrwest** [comment]
the use of `list_to_existing_atom` has been around for several versions of Riak. Allowing custom bucket properties over an external interface provides a method for a malicious client to fill the atom table. I don't like it, but we also allow arbitrary k/v pairs on bucket properties as "a feature" so disallowing things like `expiry_secs` would break that (and yes if you have a property that the atom doesn't exist for you need to create it, another reason its a bad/incomplete feature). 

I'm closing this at won't fix for housekeeping purposes. Happy to re-open or open a new issue to get rid of the arbitrary bprops "feature" if people disagree.
