### ISSUE TITLE
Poolboy Dependency

### ISSUE THREAD

**Issue by sargun** [basho/riak_core#622]
Basho's poolboy has fallen significantly far behind the upstream Poolboy. This also means that we've lost some of the benefits of the greater Poolboy project (like R17 support). It's only used in one place (riak_core_vnode_worker_pool). In my opinion, it either makes sense to upgrade to the dependency, or shed it entirely (replace it with sidejob, perhaps?)?

Does it make sense to merge the upstream Poolboy, switch entirely to the upstream Poolboy, or shed it entirely?

**Comment by seancribbs** [comment]
We had an item in the backlog to update Poolboy but it has been assigned to the 2.1 milestone.
