### ISSUE TITLE
Riak failing to start with message: "handoff.ip invalid, must be a valid IP address" #670 [JIRA: RIAK-1467]

### ISSUE THREAD

**Issue by andrewjstone** [basho/riak_core#670]
This [commit](https://github.com/basho/riak_core/pull/653) seems to have caused an issue that @coderoshi saw on friday afternoon and is now being asked about in IRC. 

It doesn't look like handoff.ip is defined at all. Adding `{handoff_ip,        "127.0.0.1"}.` into `rel/vars.config` and rebuilding with `make stagedevrel` fixes the issue. 

cc @aberghage

**Comment by andrewjstone** [comment]
This doesn't seem to be an issue anymore. Closing.

**Comment by hazen** [comment]
@andrewjstone Thanks for pointing this out. It has been trolling me recently.

**Comment by andrewjstone** [comment]
@javajolt Looks like I derped earlier. This breakage exists on develop and I only tested on 2.0. Re-testing on develop now to make sure. I will have the fix in soon.

**Comment by andrewjstone** [comment]
Oh yeah, still a problem.

**Comment by andrewjstone** [comment]
The following PRs fix this bug:
basho/riak#668
basho/riak_ee#308

**Comment by Basho-JIRA** [comment]
It turns out that this bug only existed on the develop branch of riak and riak_ee. It therefore will NOT be included in 2.0.5 and I removed that as the fix version. 

**_[posted via JIRA by Andrew Stone]**_
