### ISSUE TITLE
riak_core doesn't build on Erlang 17

### ISSUE THREAD

**Issue by marianoguerra** [basho/riak_core#708]
the flag warning_as_errors makes deprecation warnings abort the build, the warnings are:

```
src/supervisor_pre_r14b04.erl:83: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
src/supervisor_pre_r14b04.erl:83: type set/0 is deprecated and will be removed in OTP 18.0; use use sets:set/0 or preferably sets:set/1
```

a proposed solution is provided here https://blog.kempkens.io/posts/erlang-17-0-supporting-deprecated-types-without-removing-warnings_as_errors/

**Comment by marianoguerra** [comment]
fix here: https://github.com/marianoguerra/riak_core/commit/036dbfb7c84bb01999df9a3f3f8230c75f135ac5

let me know if you prefer a pull request

**Comment by cmeiklejohn** [comment]
We're hoping to target the next Riak release at Erlang 17, and we'll be addressing this in the process of doing that.  We'll most likely be pulling in upstream changes from poolboy.  Stay tuned.

**Comment by marianoguerra** [comment]
it builds now on develop, thanks!

**Comment by jadeallenx** [comment]
Yeah, lot of stuff behind the scenes last night. :)  Glad we could get this in.
