### ISSUE TITLE
erlang:now is deprecated in Erlang 18 [JIRA: RIAK-2211]

### ISSUE THREAD

**Issue by TBK145** [basho/riak_core#784]
Since erlang:now is deprecated in Erlang 18, it prevents the compilation of riak_core on Erlang 18 (http://www.erlang.org/news/88).

This should probably be replaced with erlang:timestamp (http://www.erlang.org/doc/man/erlang.html#timestamp-0).

**Comment by matehat** [comment]
Filed a pull request for that: #799
