### ISSUE TITLE
Add support for OTP 19 [JIRA: RIAK-2713]

### ISSUE THREAD

**Issue by chowevtfy** [basho/riak_core#850]
This library is falling behind and should be updated to support a modern OTP version. There's so many dependencies that it's very difficult to update the entire dependency tree to support new versions, so it'd be useful to remove dependencies as much as possible.

**Comment by hachreak** [comment]
Hi guys,
there is any news about support OTP 19? :)
I saw many PR (e.g. #785) that try to resolve the problem, but it looks like all pretty old.

**Comment by bsparrow435** [comment]
We're currently in process of bringing all our Erlang libraries to OPT18/19 compatibility. This work is slated to be finished early in the new year. Will update accordingly once dependencies have been brought up to date and the work is complete.

**Comment by ginahagg** [comment]
is this still on schedule?

**Comment by AlexanderChen1989** [comment]
anything new?

**Comment by bsparrow435** [comment]
Yes, this continues to be under active development and will be available soon although I cannot provide an exact date . One of our engineers will be giving a talk about why this has been so difficult at Erlang Factory: http://www.erlang-factory.com/sfbay2017/ted-burghart.html

**Comment by Iulian7** [comment]
Is there any progress on this? Also what about Erlang/OTP 20? When I compile with rebar3 I get a few warnings. This is also true for `cuttlefish` and `riak_ensemble`.

**Comment by martincox** [comment]
Done in develop-3.0.
