### ISSUE TITLE
Riak claim property-based tests are misleading

### ISSUE THREAD

**Issue by martinsumner** [basho/riak_core#908]
Associated with this issue is a long read:

https://github.com/martinsumner/riak_core/blob/mas-claimv2issues/docs/ring_claim.md

We have done some analysis of claim, because of a history of noting oddities about the outcomes of certain claim plans.  The headline issue we discovered was that the property-based tests make an assumption about how cluster plans are formed that does not reflect the real world, and also don't test some properties that could lead to issue sin the real world.  This means that assumptions which appear to be demonstrated to be true in the property-based tests, may commonly not be true in the real world: so bad claim behaviour is leaking into production systems.

The intention (hopefully over the next two weeks) is to both address the issues with the property-based tests, and then propose & test fixes to claim v2 which resolve these issues.  

Further details on the proposed changes are in the long read.  The reasoning for fixing v2 and not v3 is also explained.

**Comment by jadeallenx** [comment]
The document you link is excellent. 

A suggestion is that you add (perhaps toward the beginning) that in the riak system, a vnode is *the* unit of concurrency and "ring size" is essentially mapping units of concurrency to a slice of the keyspace riak manages.

**Comment by martinsumner** [comment]
Thanks for the feedback Mark.  I've added a terminology section to the top of the overview.  Does that read better for you?

**Comment by matthewvon** [comment]
Somewhere there is commentary about claim, rack awareness, and current vnode size.  This was to lead to balancing algorithms where an algorithm (I put forth a genetic algorithm and Reid proposed a standard Dijkstra algorithm ... no prototypes were created of either) would match the restrictions of rack awareness and facilitate minimized handoff of vnodes to balance against existing nodes or change in number of nodes ... I will look around.

**Comment by jadeallenx** [comment]
@martinsumner I think the glossary is great. Thanks!

**Comment by russelldb** [comment]
Going to close this, as we shipped improvements. I do think that the riak claim statem we started on needs finishing, when there is time (I'll open a new issue for that, specifically that `leave` needs modelling)
