### ISSUE TITLE
Status of risk core - is it dead?

### ISSUE THREAD

**Issue by ourway** [basho/riak_core#909]
Sorry to raise this concern.  But based on project activity I think project is slowing down.  Am I wrong?

**Comment by jeromer** [comment]
https://www.theregister.co.uk/2017/07/13/will_the_last_person_at_basho_get_the_lights_oh_too_late/

**Comment by jeromer** [comment]
A possible next step is to move the project under the [ASF](http://apache.org/) umbrella

**Comment by ourway** [comment]
So my guess was semi true.  **Basho** is dead.

**Comment by cmeiklejohn** [comment]
Riak Core is far from dead: outside of the uses inside of Riak, Lasp, Antidote, and Project FIFO are all built on Riak Core and will continue to support it independently.

**Comment by russelldb** [comment]
And the community is still coalescing. Basho maybe dead for practical purposes, but has yet to file for bankruptcy, when that finally happens the assets (including this GH org and repos) will no doubt be bought, maybe by a benefactor who wishes to rehabilitate them. In the mean time, there are the forks that cmeiklejohn has mentioned. I personally use this one https://hex.pm/packages/riak_core_ng

**Comment by cmeiklejohn** [comment]
:+1: Moving forward, the riak_core_ng package will be, as far as we can tell, the canonical version that Antidote, Lasp, and FIFO will be using and supporting.

**Comment by jeromer** [comment]
( https://www.theregister.co.uk/2017/07/31/end_of_the_road_for_basho_as_court_puts_biz_into_receivership ) 

Is there (or will there be) new official homes for Riak core/kv/cs ?

**Comment by jadeallenx** [comment]
There will eventually be an auction of intellectual property assets including the source code. Whoever buys the assets will decide what happens next. I don't think anyone knows when that auction will take place.

**Comment by victorolinasc** [comment]
Is there an update to the status here? I know that http://bet365techblog.com/riak-workshop-summary happened but I am not seeing any activity. 

Sorry if this is a bother, but I am a huge fan of the work here and will start to depend on this for a personal project, so it would be cool to have another status update.

People would love to contribute here if:

- Branches were cleaned up
- Deps were cleaned up
- Activity on issues/PRs
- Documentation updates to help people be guided through the code
- A clear list of priorities and status on those (like OTP 20 compatibility, AAE enhancemets, etc...)

Sorry if this is not the place for polling on status update.

**Comment by marianoguerra** [comment]
@victorolinasc most of the new activity is in the https://hex.pm/packages/riak_core_ng branches there's a lot of activity that should start to bear fruits in the following months.

no, it's not dead :)

**Comment by ourway** [comment]
I hope so

**Comment by russelldb** [comment]
and of course basho/riak_core continues to be improved, but with the focus being on supporting the Riak database. We've tagged riak_core for two releases since this issue was opened. And we continue to work on the basho/riak_core.

There is a lively downstream set of forks (see above.) And soon we will be moving basho /riak_core to a modern erlang.

All that said, I'm going to close this issue. If there is an outcry, we can re-open it.
